select * from emp

-- select * from EMP_SeQ

select * from EMP_SEQUENCE
--------------------------------------------------------------------------------------------
SELECT col1, col2, col3 FROM
(SELECT * FROM tableA
UNION ALL  
SELECT * FROM tableB) data
GROUP BY col1, col2, col3 HAVING count(*)!=2


	SELECT EMPNO,ENAME,JOB,MGR FROM
(SELECT EMPNO,ENAME,JOB,MGR FROM EMP 
UNION ALL
SELECT EMPNO,ENAME,JOB,MGR FROM EMP_SEQUENCE ) data
group by EMPNO,ENAME,JOB,MGR HAVING COUNT(*)!=2


--------------------------------------------------------------------------------------------
SELECT * FROM TableA UNION SELECT * FROM TableB
EXCEPT 
SELECT * FROM TableA INTERSECT SELECT * FROM TableB;


SELECT count(*),EMPNO,ENAME,JOB,MGR  countOfUnequaledColumns from (
SELECT EMPNO,ENAME,JOB,MGR FROM EMP UNION SELECT EMPNO,ENAME,JOB,MGR FROM EMP_SEQUENCE
EXCEPT
SELECT EMPNO,ENAME,JOB,MGR FROM EMP INTERSECT SELECT EMPNO,ENAME,JOB,MGR FROM EMP_SEQUENCE ) DataSet
group by EMPNO,ENAME,JOB,MGR 

-- Compare All the

SELECT EMPNO,ENAME,JOB,MGR FROM EMP INTERSECT SELECT EMPNO,ENAME,JOB,MGR FROM EMP_SEQUENCE
SELECT EMPNO,ENAME,JOB,MGR FROM EMP EXCEPT SELECT EMPNO,ENAME,JOB,MGR FROM EMP_SEQUENCE

